---
title: "upset plot"
output: pdf_document
date: "2024-12-12"
editor_options: 
  chunk_output_type: console
---

```{r}
# install.packages("msigdbr")
library(msigdbr)
library(dplyr)
library(gofigR)
enable(TRUE)

h_gene_sets<-  msigdbr(species = "human", category = "H")

h_gene_sets

head(h_gene_sets)

table(h_gene_sets$gs_name)
```


```{r}
gs_nest<- h_gene_sets %>%
  group_by(gs_name) %>%
  tidyr::nest()
```


```{r}
gs_nest$data[[1]]

gene_list<- purrr::map(gs_nest$data, ~pull(.x, gene_symbol))

names(gene_list)<- gs_nest$gs_name %>% stringr::str_replace("HALLMARK_", "")

names(gene_list)

gene_sub<- gene_list[c(13,14,15,16,18)]

names(gene_sub)
```



```{r}
library(ComplexHeatmap)
m<-  make_comb_mat(gene_sub)
m

publish(UpSet(m), "Default UpSet")

publish(UpSet(m, comb_order = order(-comb_size(m))), "UpSet with custom order")
```


```{r}
publish(UpSet(m, left_annotation = upset_left_annotation(m), 
      comb_order = order(comb_size(m))),
      "UpSet with custom order and left annotations")
```

add numbers on the bar 
```{r}
publish(UpSet(m, left_annotation = upset_left_annotation(m), 
      top_annotation = upset_top_annotation(m, add_numbers = TRUE),
      comb_order = order(comb_size(m))),
      "UpSet with custom order and right annotations")
```

change set order 
```{r}
publish(UpSet(m, 
      left_annotation = upset_left_annotation(m), 
      top_annotation = upset_top_annotation(m, add_numbers = TRUE),
      set_order = c("E2F_TARGETS","G2M_CHECKPOINT","ESTROGEN_RESPONSE_EARLY",
                    "ESTROGEN_RESPONSE_LATE", "EPITHELIAL_MESENCHYMAL_TRANSITION"),
      comb_order = order(comb_size(m))),
      "UpSet with custom set order")
```

```{r}
publish(UpSet(m, 
      left_annotation = upset_left_annotation(m), 
      top_annotation = upset_top_annotation(m, add_numbers = TRUE),
      set_order = c("E2F_TARGETS","G2M_CHECKPOINT","ESTROGEN_RESPONSE_EARLY",
                    "ESTROGEN_RESPONSE_LATE", "EPITHELIAL_MESENCHYMAL_TRANSITION"),
      comb_order = order(-comb_size(m))),
      "UpSet with reverse comb order")
```

Change the rowname size 

```{r}
publish(UpSet(m, left_annotation = upset_left_annotation(m), 
      top_annotation = upset_top_annotation(m, add_numbers = TRUE),
      comb_order = order(comb_size(m)),
      row_names_gp = gpar(fontsize = 8)),
      "UpSet with row names")
```
